### PR TITLE
refactor(store): replace `for-of` with oldie for loops

### PR DESCRIPTION
**Pull request by arturovt**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

`for-of` is actually used to iterate over ANY iterable (map, set, etc...). TS compiler emits `__value` helper when targetting ES5, which supports ES2015 iteration protocol.

See how much code is emitted:
---
image
---
image

There are a lot of `try-catch-finally` calls. We wouldn't want them when we just wanna loop over a single array. It seems like the bundlesize grew (from 18.67 to 18.74), but no. This is because the bundlesize package checks es2015 files and not es5.

I just checked the size of `@ngxs/store/bundles/ngxs-store.umd.min.js` (**it's minified**). It was 32KB before this refactoring and became 30KB after.

ES5 is still important for old browsers. *And if the user uses old browser then the bundlesize really matters and those unnecessary emitted `try-catch-finally` blocks can slow the code execution on older browsers*.

### CODE REVIEW

**Comment by splincode** [comment]
@markwhitfeld In total (taking into account the difference of the two packages) savings in `0.5kB`. I think this is also a good result.

**Comment by arturovt** [comment]
Don't worry guys, I will reopen it with more changes a little bit later!

**Comment by arturovt** [comment]
Max, please, do not push to other members PRs w/o negotiation. I had to cherry pick your last commit to retrieve those changes locally, also I ain't able to squash :(

**Comment by splincode** [comment]
@arturovt can be merge?

**Comment by arturovt** [comment]
> @arturovt can be merge?

Don't know, do we need Mark's approve?

**Comment by markwhitfeld** [comment]
I don't think that we should make the change to check against the uncompressed sizes in this PR. It makes the effect on build sizes more difficult to understand within this PR.

Also, are we wanting to smake our modern bundle size larger (and the code less modern) to make it smaller for old browsers?

**Comment by arturovt** [comment]
> I don't think that we should make the change to check against the uncompressed sizes in this PR. It makes the effect on build sizes more difficult to understand within this PR.
> 
> Also, are we wanting to smake our modern bundle size larger (and the code less modern) to make it smaller for old browsers?

Basically, this change will not affect modern browsers (swapping from `for-of` to a single `for` loop). But this will affect older browsers.

**Comment by markwhitfeld** [comment]
Honestly, I feel like this is a micro-optimisation that has little value.
Close it if you agree.

**Comment by arturovt** [comment]
> Honestly, I feel like this is a micro-optimisation that has little value.
> Close it if you agree.

Agreed.

**Pull request closed without merging**
