### PR TITLE
fix: overload `ModuleWithProviders` type to make it Ivy compatible

### PR DESCRIPTION
**Pull request by arturovt**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

image

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

NG5 tests prolly will fail but there is a PR that skips support for NG5.

### CODE REVIEW

**Comment by arturovt** [comment]
@splincode ping. Should this PR be a part of the next release as we drop NG5?

**Comment by splincode** [comment]
@arturovt I suggest making a separate PR which add all types to all plugins at once. After we hold my PR (https://github.com/ngxs/store/pull/1464)

**Comment by arturovt** [comment]
> @arturovt I suggest making a separate PR which add all types to all plugins at once. After we hold my PR (#1464)

I can update this PR and just amend the commit message + PR title. What do you think?

**Comment by splincode** [comment]
@arturovt Very good idea

**Comment by arturovt** [comment]
Basically, after your last PR the router plugin is compatible with Ivy :rocket:

**Comment by markwhitfeld** [comment]
Merging this. The build is happy (except for Travis, which is experiencing issues at the moment).

**Pull request merged**
