### PR TITLE
build: add build integration test with Angular 9-next.14

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

image

Issue Number: https://github.com/ngxs/store/issues/1165

## What is the new behavior?

explicit type specification in ModuleWithProviders

image

image

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by splincode** [comment]
@markwhitfeld  codeclimate?!

**Comment by splincode** [comment]
image

Angular 5 not supported generic for ModuleWithProviders

image

Since Angular 9 we need pass type to ModuleWithProviders

**Comment by splincode** [comment]
@markwhitfeld  What do you think?

**Comment by splincode** [comment]
Breaking Changes for user uses Angular 5
Now we uses only minimal Angular v6.1.1, TS 2.8.1 for corrects supported Angular 9+.

**Comment by splincode** [comment]
Codeclimate (please fix)

**Comment by splincode** [comment]
image

Officially, we need to abandon Angular 5 support, just as the Angular team did.

**Comment by markwhitfeld** [comment]
Hmmm... we may have to do this in NGXS v4

**Comment by splincode** [comment]
Not sure, because without it, we can't support new Angular

**Comment by splincode** [comment]
How long does it take to get to version 4?

**Pull request closed without merging**
