### PR TITLE
WIP: chore(store): type safety & lazy testing

### PR DESCRIPTION
**Pull request by deebloo**
This PR shows how we can setup and test lazy loaded modules to help us track down issues with lazy loading.

THIS IS HERE FOR REFERENCE AND TO SHOW PROGRESS. 

DO NOT MERGE

### CODE REVIEW

**Comment by leon** [comment]
@deebloo It's great that we can test lazy stuff now. great work!

**Comment by deebloo** [comment]
@leon feel free to add more tests and such to this branch

**Comment by amcdnl** [comment]
@deebloo - Where are w/ this?

**Comment by deebloo** [comment]
Haven't had a chance to work on ngxw for a couple days.

**Pull request closed without merging**
