### PR TITLE
docs: introduce deprecation root pages

### PR DESCRIPTION
**Pull request by profanis**
The reason for this change is the following:

Let's assume a developer works in a company where they decide to migrate to the version where the select decorator is deprecated. Although it's being deprecated they might need some time to convert their code. At the same time, they might need/want to read about the select decorator. If we completely remove the docs, it's harder for them to find the information they are looking for

image

### CODE REVIEW

**Review by arturovt — APPROVED** [review]

**Review by markwhitfeld — COMMENTED** [review]
We need to update the docs references in the deprecation doc comments in the actual code too.

**Comment by profanis** [comment]
> We need to update the docs references in the deprecation doc comments in the actual code too.

@markwhitfeld I am afraid I didn't get what needs to be fixed.

**Comment by arturovt** [comment]
I think Mark refers to this code:

image

**Comment by arturovt** [comment]
And for `children` too

**Comment by profanis** [comment]
> We need to update the docs references in the deprecation doc comments in the actual code too.

I updated the doc references @markwhitfeld

**Pull request merged**
