### PR TITLE
fix(store): do not try to decorate factory asynchronously

### PR DESCRIPTION
**Pull request by arturovt**
I added the same unit test both for ng13 and ng14, since ng13 uses Jest and ng14 uses Karma.

Issue: #1855
Issue: #1854

### CODE REVIEW

**Review by markwhitfeld — COMMENTED** [review]
Awesome! Does this resolve all the issues, or are there cases where there may still be issues?

**Comment by arturovt** [comment]
> Awesome! Does this resolve all the issues, or are there cases where there may still be issues?

I believe those issues are related to each other. I'll ask people to install the `dev` version and try it out.

**Comment by arturovt** [comment]
@markwhitfeld is that ok to be merged?

**Review by markwhitfeld — APPROVED** [review]
If there is no other way, then I guess this is what we must do.
Just before you go ahead and merge, I was wanting to ask if there was an alternative that leverages the Jest or Karma/Jasmine test contexts directly that could potentially result in a neater approach?
Or even potentially putting metadata on the ZoneJs context during tests?

**Comment by arturovt** [comment]
As I messaged in slack I really haven't found any other options. Let's merge and see if users will experience other issues.

**Comment by arturovt** [comment]
@markwhitfeld can you allow the publish because github actions say "Waiting for review: npm-publish needs approval to start deploying changes."?

**Pull request merged**
