### PR TITLE
fix(router-plugin): serialize after `ResolveEnd`

### PR DESCRIPTION
**Pull request by arturovt**
## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Issue Number: #481 

## What is the new behavior?
Right now `serialize` is triggered in the `beforePreactivation` hook. Before preactivation is handled before running guards and resolvers. I've moved it to the `ResolveEnd` hook

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by arturovt** [comment]
@splincode @markwhitfeld @eranshmil 
The current implementation uses `RouterStateSnapshot`. After investigation I've found that it's basically impossible to access resolved data, because the `data` property can be inside 4 nested `firstChild` objects.

**Comment by eranshmil** [comment]
This is a breaking change. :(

**Comment by arturovt** [comment]
@eranshmil okay, I'm gonna try to minimize changes

**Comment by arturovt** [comment]
@eranshmil @splincode ping

also guys what do you think about adding a new selector to the `RouterState` that will resolve the `ActivatedRouteSnapshot` linked to provided component? Basic example:

```TS
// pseudocode
static findActivatedRouteThatLinkedWithComponent<T>(component: Type<T>, snapshot: ActivatedRouteSnapshot) {
  let route = snapshot;

  while (route && route.component.constructor !== component) {
    route = route.firstChild;
  }

  return route;
}

static activatedRoute<T>(component: Type<T>) {
  return createSelector([RouterState], (state: RouterStateModel) => {
    return this.findActivatedRouteThatLinkedWithComponent(component, state.state.root);
  });
}
```

So people can use it like:

```
export class TodosComponent {
  @Select(RouterState.activatedRoute(TodosComponent)) public route$;
}
```

**Comment by arturovt** [comment]
@eranshmil @splincode @markwhitfeld

**Comment by splincode** [comment]
@eranshmil why is it a breaking changes?

**Comment by markwhitfeld** [comment]
@splincode why did you delete @eranshmil 's comment?

**Comment by splincode** [comment]
@eranshmil in the chat he replied that this is not a breaking change

**Comment by markwhitfeld** [comment]
Ok, rather add a new comment to the thread than delete.
Delete is really only reserved for if there is some profane or abusive comment.

**Comment by arturovt** [comment]
@splincode I had a breaking change in the first commit

**Comment by splincode** [comment]
@markwhitfeld sorry :(

**Comment by markwhitfeld** [comment]
@splincode no worries 👍 
@arturovt I saw that you fixed it after Eran's comment
Could I get your feedback on this
> @arturovt Just one question, it does make sense to me that the snapshot should happen on `ResolveEnd`, but do you think that there could have been any reason for someone to expect it to happen in `beforePreactivation` instead?
> Just checking if this could be a breaking change for a reasonable use case...

**Comment by arturovt** [comment]
@markwhitfeld umm, I'm not sure if it's a breaking change... I guess I could add more tests there but it's hard to test route snapshot as they dont work with `RouterTestingModule`, so I was able to add only SSR tests :fearful:

**Comment by markwhitfeld** [comment]
Yeah, not worried about the tests, those look fine.
Was just wondering if there could be some wierd case where someone would actually want the previous behaviour.

**Comment by arturovt** [comment]
@markwhitfeld I've heard from @eranshmil that he actively used this plugin on some project(s). Eran what do you think?

**Comment by markwhitfeld** [comment]
I was just thinking, is there any difference between if this was dispatched on `NavigationEnd` as opposed to `ResolveEnd`? Not particularly wanting to change, but just interested in what more the later event could offer...

**Comment by arturovt** [comment]
`NavigationEnd` instance has only string information about the last navigation - `id` and `urlAfterRedirects`

**Comment by eranshmil** [comment]
> Looks good to me.
> @arturovt Just one question, it does make sense to me that the snapshot should happen on `ResolveEnd`, but do you think that there could have been any reason for someone to expect it to happen in `beforePreactivation` instead?
> Just checking if this could be a breaking change for a reasonable use case...

Sorry for the late answer.
I don't remember what I wrote in here, but this is what **might** be a breaking change. In ngrx, they added a new option to the config.
But, just like you, I also think it should be that way. 😆

**Pull request merged**
