### PR TITLE
feat(store): expose StateClass for @ngxs/store/testing

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by markwhitfeld** [comment]
Why do we need this exposed?

**Comment by splincode** [comment]
@markwhitfeld This is necessary in order to use in individual plugins.  I have a plan for refactoring.

```states: StateClass[]```

instead

```states: any[]```

**Comment by splincode** [comment]
@markwhitfeld I will add this to the Public API so that we can take advantage of it.
https://github.com/ngxs/store/pull/1034

**Comment by markwhitfeld** [comment]
This should deninitely not be exposed because it exposes the META_KEY etc.
Reverting this. Please don't merge PRs without approval.

**Comment by markwhitfeld** [comment]
Once used from the internals subpackage it sets up a circular dependency between the main package and the subpackage

**Pull request merged**
