### PR TITLE
Refactor(storage-plugin): Rework storage

### PR DESCRIPTION
**Pull request by un33k**
Restrict storage types to localStorage and sessionStorage.
Reintroduce NgxsStorageStrategy.

Fix for https://github.com/ngxs/store/issues/140

### CODE REVIEW

**Comment by amcdnl** [comment]
We want to allow you to pass in the storage strategy you want so that you can swap it out for various different platforms like mobile.

**Comment by amcdnl** [comment]
We wanted to expose it where you can pass the different storage engines if you are on different platforms, for instance mobile.

Reading through the issue, I wonder if is another way to handle this.

**Comment by un33k** [comment]
I put inline instructions in the options. 

For mobile there is no localStorage or sessionStorage. 

So a compatible store engine would be used like:

Import {customLocalStoage} from ‘some-storage-package’;

global.localStorage = customLocalStorage. 

Ditto for sessionStorage. 

That is done in the app module. 

The PR takes care of everything else. 

Val

**Comment by deebloo** [comment]
I don't like having to globally set the storage engine. that feels very hacky. I think we can provide a way to make this happen but i don't think this is it

**Comment by deebloo** [comment]
I think we are better suited providing an injection token and interface for what storage looking like that a user can then provide whatever solution they want and we can still provide an enum for the defaults of localstorage and sessionstorage.

**Comment by deebloo** [comment]
@un33k I am closing this for now since the repo is going through some significant restructuring and we can address after that get's merged in

**Comment by un33k** [comment]
@deebloo @amcdnl Sounds good.

**Pull request closed without merging**
