### PR TITLE
Update entity class branch with changes in master and immutability

### PR DESCRIPTION
**Pull request by juracy**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] Other... Please describe:Update branch with master code

## What is the current behavior?
- The impossibility to merge this branch into master
- It doesn't work in development mode (immutable)

Issue Number: N/A

## What is the new behavior?
- The ability to merge into Master
- It works in development mode

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by juracy** [comment]
Fixes in entity class for developmentMode (immutable)

**Comment by splincode** [comment]
@markwhitfeld Is this relevant? There are too many changes

**Comment by markwhitfeld** [comment]
This branch probably needs to be grenades on master as opposed to a merge from master. We are figuring out what we want to do with the entity stuff at the moment so this is on hold

**Comment by juracy** [comment]
This PR is basically changes from master merged to entity class branch and some conflicts fixes...
The current entity class branch has conflicts with master...

**Comment by splincode** [comment]
@juracy development moved to separate repository
https://github.com/ngxs-labs/entity-state/

If you're interested, I can give you access.

**Pull request closed without merging**
