### PR TITLE
perf(store): tree-shake `deepFreeze`

### PR DESCRIPTION
**Pull request by arturovt**
## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit

## PR Type
```
[x] Refactoring (no functional changes, no api changes)
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by splincode — APPROVED** [review]

**Comment by splincode** [comment]
@arturovt hello, please, trigger CI

**Comment by splincode** [comment]
really strange, why CI works for PR https://github.com/ngxs/store/pull/1820

**Comment by arturovt** [comment]
Circle doesn't like me.

**Comment by splincode** [comment]
I really want migrate to Github Actions, it's easy for support

@arturovt @markwhitfeld what do you think?

**Comment by markwhitfeld** [comment]
@splincode Yes, I agree, although there is nothing stopping us from leveraging both.
You were going to work on this a few months back. Did you look at this at all?
https://github.com/ngxs-labs/platform/issues/1

**Comment by splincode** [comment]
@markwhitfeld after moving to a new team (https://github.com/tinkoff/taiga-ui), I could not yet find the time ((

**Review by markwhitfeld — APPROVED** [review]

**Pull request merged**
