### PR TITLE
refactor(store): decompose selectorOptionsMetaAccessor

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

In our project, we needed to dynamically define the selector options

## What is the new behavior?

Now we can dynamically set the settings in runtime

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by arturovt** [comment]
Can we have some PR description?

* Use cases
* How can our users benefit from this feature

**Comment by splincode** [comment]
@markwhitfeld @arturovt only a refactor and tests to understand that property merging works correctly

**Comment by markwhitfeld** [comment]
@splincode What is the reason for decomposing `selectorOptionsMetaAccessor`?
It was made that way in order to keep the concerns isolated from the other meta stuff.

Also, what is the motivation for this refactor? What need is it fulfilling?

**Comment by splincode** [comment]
The code looks more understandable and tests are added to it

**Comment by splincode** [comment]
Firstly, If we need to make the API as public, as is done with ` getSelectorMetadata, getStoreMetadata, ensureStoreMetadata, ensureSelectorMetadata`, It will be enough for us only to export in public_api.ts

Secondly, the decomposition of the `selectorOptionsMetaAccessor` object into more understandable operations: `defineSelectorOptions`, `getSelectorOptions`.

**Comment by arturovt** [comment]
Max, it would be really great if you’d taken some opened issue. Could we **primarily focus bugs**?
I can sound pedantic but refactoring shouldn’t break the YAGNI principle.
I understand the selectorOptionsMetaAccessor as well, so I cannot say that it’s confusing or something. My concern is that we will not benefit from this decomposition. I’m sure 100% that you, Mark and me can understand this piece of code readily. I think that the selectorOptionsMetaAccessor is also testable, as the new decomposed part.

**Pull request closed without merging**
