### PR TITLE
Docs/ngxs labs

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by splincode** [comment]
because markdown is harder to maintain for tables

**Comment by eranshmil** [comment]
It's really easy to maintain with the following VSCode extension:
https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one

**Comment by markwhitfeld** [comment]
@splincode Why did you merge this when there were no approvals?
I would prefer that we stick with what markdown offers in markdown files ie. markdown tables
HTML being easier to maintain is a matter of opinion. 

@eranshmil , that tool is great!

**Comment by splincode** [comment]
ok, I'll roll it

**Pull request merged**
