### PR TITLE
feat(form-plugin): ngxsForm directive takes in an observable that triggers saving

### PR DESCRIPTION
**Pull request by JanMalch**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added
- [x] Docs have been added / updated

(I'm unsure how to write a test for this feature and would appreciate some help.)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

When using the form directive all input values will automatically be stored.

## What is the new behavior?

This PR introduces the option to control this behaviour with an observable, to allow saving via button clicks or similar events. With this implementation it replaces the auto-saving behaviour.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

Here's an example for how this can be used (based on the integration app)

#### app.component.ts (relevant parts)

```typescript
@Component({
  selector: 'app-root',
  template: `
        <form [formGroup]="pizzaForm" novalidate (ngSubmit)="onSubmit()" ngxsForm="todos.pizza" [ngxsFormStoreOn]="saveRequests$">
  `
})
export class AppComponent {
  saveRequests$ = new Subject<void>();

  onSubmit() {
    this.saveRequests$.next();
  }
}
```

### CODE REVIEW

**Comment by splincode** [comment]
@JanMalch Could you add tests?

add here
https://github.com/ngxs/store/blob/c42f83e6f9220d8b8950ef725b259c644ac21c18/integration/app/app.component.spec.ts

**Comment by JanMalch** [comment]
I had to create a second form as other tests wouldn't work anymore. I hope the test suffices.

**Comment by splincode** [comment]
@JanMalch need fix test (CI failed)

**Comment by JanMalch** [comment]
The tests work fine on my machine. In the circle-ci log it also says **6 of 6 SUCCESS**.

```
Chrome 69.0.3497 (Linux 0.0.0): Executed 6 of 6 SUCCESS (1.064 secs / 0 secs)
Chrome 69.0.3497 (Linux 0.0.0) ERROR
  {
    "message": {
      "isTrusted": true
    },
    "str": "[object ErrorEvent]"
  }
```

If you can explain me what is going wrong I can try to fix it.

**Comment by splincode** [comment]
https://github.com/karma-runner/karma/issues/2852

**Comment by markwhitfeld** [comment]
@JanMalch Maybe wrapping the body of your test in a `fakeAsync` call may solve this problem... Worth trying out.
I like this feature too but I think that there could possibly be a better name for the `ngxsFormStoreOn` property. What other ideas do you have for names for this?

**Comment by JanMalch** [comment]
@markwhitfeld I originally used `fakeAsync` but it didnt work either. It had a `tick(200)` in it. I could try again with `fakeAsync` but without `tick(200)` ...

In alignment with RxJs maybe something like `storeWhen`? Or `triggerSave`, `triggerStoring`, `storeTrigger` or any other combination. I think it should indicate that it's a trigger (`When` or `trigger`) and what it does (`save` / `store`)

**Comment by splincode** [comment]
@JanMalch Did you manage to solve the problem?

**Comment by JanMalch** [comment]
@splincode unfortunately not. I got no new ideas.

**Comment by JanMalch** [comment]
@splincode @markwhitfeld What can we do here? I don't have the ideas and time currently to fix this. Does it make sense to make you a collaborator so you can try to fix this, if you want?

**Comment by splincode** [comment]
@markwhitfeld ping

**Comment by splincode** [comment]
@JanMalch out of date

**Pull request closed without merging**
