### PR TITLE
feat: add support for angular 13

### PR DESCRIPTION
**Pull request by internalsystemerror**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Angular 12 max supported version

## What is the new behavior?

Angular 13 max supported version

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

Closes https://github.com/ngxs/store/issues/1797

### CODE REVIEW

**Comment by internalsystemerror** [comment]
This is marked as a draft PR (maintainers are ofc welcome to take control over this) and so far allows the Angular 13 installation, and has an added ng13 integration test.

**Comment by internalsystemerror** [comment]
This is currently blocked by https://github.com/angular-eslint/angular-eslint/issues/715, using the `next` version of this package succeeds (at least locally), so a simple upgrade once this is released should suffice.

**Comment by splincode** [comment]
Good job!

**Comment by internalsystemerror** [comment]
I realised over this weekend that I'd run the integration test against the wrong project so I decided to take another look. In order to run ng update against a copy of the v12 integration, I had copied this into a different project, ran the upgrade and then copied it back. Upgrading `@angular-eslint/angular-eslint` fixed the issue for my other project, however `@angular-eslint/angular-eslint` is not used in this project.

So upon taking another look, it is `@angular-builders/jest` (v11) that is throwing the error here and upgrading to v13 of this package fixes it. However, I'm still struggling to get set up running these integrations correctly so I will fix any subsequent issues that are flagged in CI.

**Review by splincode — APPROVED** [review]
Great job 👏

**Comment by irowbin** [comment]
Tests depending on `ngxs` are failing after Angular v13 upgrade. I think this is the PR that resolves those.?

**Comment by splincode** [comment]
@irowbin could you please provide a minimum repo so that we can check if this is so

**Comment by razmjo-netlinks** [comment]
Guys, I am waiting for this pull request. I need to upgrade to angular 13.

**Comment by irowbin** [comment]
> @irowbin could you please provide a minimum repo so that we can check if this is so

@splincode The same tests works on v12 but the same test doesn't work on v13 as it prints:
```ts
Error: Unexpected value 'NgxsRootModule' imported by the module 'DynamicTestModule'.
Please add an @NgModule annotation.

```

Not sure if this is due to `.mjs` extension  by v13 packager or something like that. We use `jest` so haven't check on `jasmine/karma`

**Comment by jonaskuske** [comment]
@irowbin Try to re-run `npx ngcc`, that helped when I saw that error

**Comment by splincode** [comment]
@jonaskuske @irowbin @internalsystemerror try install `@ngxs/store@dev`

image

**Comment by internalsystemerror** [comment]
> @irowbin Try to re-run `npx ngcc`, that helped when I saw that error

This is something that I also had to do multiple times during the update from v12 to v13 in this PR. The first round of ngcc fails due to the package format change... The second round seems to ignore anything previously and reruns everything.


> @jonaskuske @irowbin @internalsystemerror try install `@ngxs/store@dev`

Our projects using `@ngxs/store` and the related plugins are all still stuck on v12 of angular even with this as we have other dependencies such as `@ng-bootstrap/ng-bootstrap` which still require v13 support.

**Comment by markwhitfeld** [comment]
Hi @internalsystemerror and everybody else.
Apologies for being off the radar on this. I have been head down collaborating with the Angular team, adding NG13 support to StackBlitz has been no small task. The Ivy partial package format is easy, it's the `mjs` files and `exports` in `package.json` that is making it a real challenge. Anyway, that's another story.

My aim is to get this NGXS release out in the next few days.

**Comment by suer85** [comment]
Just curious if there is any status update on this?

**Comment by splincode** [comment]
@markwhitfeld @arturovt any news?

@suer85 hello) we are blocked by https://github.com/ngxs/store/pull/1804

**Comment by bendehghan** [comment]
Hey guys, will there be a build that supports angular 13? The last release is well before the angular update. Pretty soon we'll be at angular 14...

Thanks!

**Comment by splincode** [comment]
@bendehghan hello, use `3.7.3`

image

**Comment by bendehghan** [comment]
I see. Thanks. 
3.7.3 is only a tag. I kept looking in the releases and didn't think of tags.

I get this on 3.7.3. Is that an issue on my side or yours?
`
Processing legacy "View Engine" libraries:
- @ngxs/devtools-plugin [es2015/esm2015] (git+https://github.com/ngxs/store.git)
- @ngxs/storage-plugin [es2015/esm2015] (git+https://github.com/ngxs/store.git)
- @ngxs/store/internals/testing [es2015/esm2015] (git+https://github.com/ngxs/store.git)
- @ngxs/store/operators [es2015/esm2015] (git+https://github.com/ngxs/store.git)
- @ngxs/store/internals [main/umd] (git+https://github.com/ngxs/store.git)
- @ngxs/devtools-plugin [main/umd] (git+https://github.com/ngxs/store.git)
- @ngxs/store [main/umd] (git+https://github.com/ngxs/store.git)
- @ngxs/logger-plugin [main/umd] (git+https://github.com/ngxs/store.git)
- @ngxs/router-plugin [main/umd] (git+https://github.com/ngxs/store.git)
- @ngxs/storage-plugin [main/umd] (git+https://github.com/ngxs/store.git)
- @ngxs/store/internals/testing [main/umd] (git+https://github.com/ngxs/store.git)
- @ngxs/store/operators [main/umd] (git+https://github.com/ngxs/store.git)
Encourage the library authors to publish an Ivy distribution.

`

**Comment by internalsystemerror** [comment]
@bendehghan I believe that's planned for v4, it was mentioned in here: https://github.com/ngxs/store/issues/827

**Pull request merged**
