### PR TITLE
refactor: improve state operator typings

### PR DESCRIPTION
**Pull request by arturovt**
## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
The current typings are not explicit

## What is the new behavior?
To add explicit return type typings for the state operators.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by splincode** [comment]
https://github.com/markwhitfeld/store/blob/8b92796ba9c8c815bafed40c3c2fb3fe5b50ff56/packages/store/types/tests/state-operators.iif.lint.ts

**Comment by arturovt** [comment]
Yeah, I forgot, I will paste today

**Comment by splincode** [comment]
I almost fixed the problem and want to add changes

**Comment by arturovt** [comment]
Need to notify Mark because he's also working on the fix

**Comment by splincode** [comment]
@markwhitfeld @arturovt Guys, I suggest to make release of version 4.0.0. Because 3.5.0 includes a huge number of changes, and it can break everything.

- Where we will do support Angular 8 and go to support only TypeScript 3+.
- It will also explain why we delayed the release so long.
- And also we can make a number of changes that we wanted to make as part of the task: https://github.com/ngxs/store/issues/827

**Comment by arturovt** [comment]
@splincode 
```TS
(async () => await Mark())()
```
:joy:

**Comment by arturovt** [comment]
I guess that we could release 3.5 with those changes that we ALREADY HAVE, like router/web-socket plugins bug fixes and blah blah.
But I'm afraid that operators and Angular 8 could be really a breaking change so it should be v4 release.
Also the problem is that Angular 8 uses typescript 3.4 and it has performance issues that were fixed in 3.5, I'm just wondering why Angular team doesn't want to upgrade the TS version.

**Comment by splincode** [comment]
We can make backports with bugfixes for 3.4.4 , but I would send new features to version 4 and make such a release.

**Comment by arturovt** [comment]
We have a lot of bug fixes so minor patch to the v3.5 is very ok and can be satisfied by semver philosophy, like if we fixed only 1 bug - then 3.4.4 would be ok.

My point is:
`v3.5 (with a lot of bug fixes) --> v4 (Angular 8 / TS 3.4(or 3.5) + typings improvement`

**Comment by splincode** [comment]
@arturovt Okey, up to you

**Comment by splincode** [comment]
@arturovt But why we waited for release v3.5 so long? More people want integrated Angular 8. I think we have to drop the shackles of legacy

**Comment by arturovt** [comment]
The problem is that now only a small part of the projects is being transferred to the new version of Angular. That's just statistics, not my subjective opinion. I've got only 1 project that uses Angular 8 in my company - mine :joy: Other projects still use Angular 6-7. 

v3.5 is for those people who cannot migrate to the new Angular, but they will receive our bug fixes, e.g. those who use router plugin. And v4 is for those who migrated to the Angular 8.

If we move those bug fixes to the v4 - so people are not able to get them (because they don't use Angular 8).

> But why we waited for release v3.5 so long?

I cannot do releases w/o Mark :(

**Comment by splincode** [comment]
In general, this is a big question that is difficult to answer. But I’m completely upset that we don’t have release schedules.

**Comment by markwhitfeld** [comment]
Unfortunately some of these changes to the state operator typings are indeed breaking changes.
We still need to get NGXS v3.5 out before NGXS v4 to help with the transition. Also if we start bundling these things into a v4 release it will delay it even further!

It would also be my preference if we could keep the implicit nature of the state operators... this has become an even bigger challenge with TS 3.4.

I have realized though that the issue with the typings has been introduced by breaking changes in TS and not in NGXS, so I will have a look to see what the minimum is that we can do to soften the TS3.5 transition without breaking compatibility for those on earlier versions of TS. If someone upgrades to Angular v4 and TS3.5 they will be fixing types because of that upgrade, not because of NGXS.

I will be getting deep into this in the next few days.

PS. @splincode those tweaks to the patch operator typings look amazing, I need to get my head around them because it was such a balancing act to get that right in the first place (then maybe they can be lined up for v4).

**Comment by markwhitfeld** [comment]
I'm closing this PR because I would not want to lose the implicit state operator functionality.
... and if the changes on master work then we don't need these changes.

**Pull request closed without merging**
