### PR TITLE
fix(hmr): actions type consistency

### PR DESCRIPTION
**Pull request by eranshmil**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
After the commit, I tested again with the `@dev builds` but it works with typescript 2.*, so I leave this PR only for consistency with the other action types defined in the project.

Related PRs:
#644 
#765 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by splincode** [comment]
image

**Comment by arturovt** [comment]
@splincode this can be skipped :wink:

**Comment by splincode** [comment]
@arturovt real shit :(

**Comment by arturovt** [comment]
@markwhitfeld ping :rocket:

**Pull request merged**
