### PR TITLE
feat(declareAction): allow declarations of actions outside of state-classes

### PR DESCRIPTION
**Pull request by duffleit**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the new feature about?
Especially large codebases can get the issue of ending up in sprawling and hard to test NGXS-state-classes. Breaking the state into smaller chunks is not always an option, especially when the data is very cohesive and the interaction between it is complex.

Thus we wanted to move actions into independent, testable and simple to grasp files. For this purpose, a small helper function was introduced which allows the declaration of actions which are handled outside of the state class.

Following this approach brought us in the desirable condition to have all actions and usefully grouped selectors in separate classes. Our file structure in large enterprise applications therefore usually looks ruffly like this:

```
/store
  /shop
    shop.state.ts
    shop.actions.ts
    actions/ 
      add-product-to-cart.action.ts
      add-product-to-cart.action.spec.ts
      fetch-products.action.ts
      fetch-products.action.spec.ts
    selectors/
      products.selector.ts
      prices.selector.ts
```

The responsibility of the state-class itself is just to group und bootstrap all the action declarations: 

```
@State<ShopStateModel>({ name: 'shop', defaults: DEFAULT_SHOP_STATE })
export class ShopState {
  constructor(productService: ProductService) {
    declareAction(ShopState, AddProductToCartAction, addProductToCart);
    declareAction(ShopState, FetchProductsAction, fetchProducts(productService));
    declareAction(ShopState, AnotherAction, ...);
    declareAction(ShopState, [ActionA, ActionB], ...);
  }
}
``` 

The actions are just idiomatic (higher-order) functions: 
```
export const addProductToCart =
  (ctx: StateContext<ShopStateModel>, act: AddProductToCartAction) => {
    ctx.patchState({cart: [act.product]})
}

export const fetchProducts =
  (productService: ProductService) =>
    (ctx: StateContext<ShopStateModel>, act: FetchProductsAction) => {
      productService.fetchProducts().subscribe(products => {
        ctx.patchState({products})
      });
    }
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by splincode** [comment]
@duffleit Thank you so much for your contribution, but I would recommend that you make a plugin for NGXS, and not make such changes to the main repository!

**Comment by arturovt** [comment]
Haven't had a chance to look at the PR's codebase, but as @splincode mentioned, yes. Most features we transfer to the *ngxs-labs* thus we give users an opportunity to "play" with this feature. Then we gather to discuss and transfer it to the main repository.

**Comment by arturovt** [comment]
@duffleit I can create a repository for you and give the rights, how would you like it to name? Is **ngxs-labs/declare-action** OK?

**Comment by duffleit** [comment]
Sounds good, let’s go for this!

**Comment by arturovt** [comment]
@duffleit 

I've added you as a collaborator with **Write** permissions https://github.com/ngxs-labs/declare-action

**Comment by arturovt** [comment]
You can take our skeleton https://github.com/ngxs-labs/skeleton, it hasn't been updated for a while, just need to update packages there :D

**Comment by arturovt** [comment]
Just install the dependencies and run `yarn create-project --name declare-action`

**Comment by markwhitfeld** [comment]
I agree with @splincode and @arturovt. It would be great to add this as a labs project to allow for iteration and then assess it once it is stable.
I think that we could also think about potential alternative names for this...
We would want something that makes it really obvious as to what it offers.

**Comment by markwhitfeld** [comment]
Potentially a good names: `connect-action` or `attach-action`
Any other ideas?

**Comment by duffleit** [comment]
The term `connect` is often used to connect components with a store in the redux world, thus i would go for `attachAction`.

**Comment by markwhitfeld** [comment]
Good point. When I read `declareAction` my first reaction was "What does this do?". Just declaring something usually doesn't do much. With this in mind do you think that `attachAction` would convey the meaning better?

**Comment by splincode** [comment]
@markwhitfeld we can close?

**Comment by markwhitfeld** [comment]
Yes, I think we can close.

**Comment by duffleit** [comment]
@markwhitfeld, @splincode could you create the corresponding `package` on npmjs.com?

**Comment by splincode** [comment]
@duffleit give me your npm login

**Comment by splincode** [comment]
@duffleit https://www.npmjs.com/package/@ngxs-labs/attach-action

**Comment by duffleit** [comment]
@splincode - my npm login is: duffleit - thx!

**Comment by splincode** [comment]
@duffleit I added package management rights for you on NPM

**Comment by duffleit** [comment]
One last thing, could you set the github repo description to: `⚡️ Attach independent, pure and easy to test Action Handlers to NGXS States.` I cannot change this one. :)

**Pull request closed without merging**
