### PR TITLE
build: add cypress for E2E testing

### PR DESCRIPTION
**Pull request by arturovt**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
Max and me are working on the good-looking integration example, currently we're working on the wireframes. Cypress will allow us to write integration tests for our "showroom" application. This will ensure that all the integrated pieces of an application function and work together as expected with NGXS.

Also there are some pieces of functionality that cannot be tested directly using Jest (e.g. router plugin issues).

Also we don't test the behavior of all plugins together.

### CODE REVIEW

**Comment by arturovt** [comment]
@markwhitfeld Max and me are working on the good-looking integration example, currently we're working on the wireframes. Cypress will allow us to write integration tests for our "showroom" application. This will also ensure that all the integrated pieces of an application function and work together as expected with NGXS.

that all the integrated pieces of an application function and work together as expected

**Comment by arturovt** [comment]
OK, this Circle makes me crazy, will play with it in my Circle sandbox.

**Comment by markwhitfeld** [comment]
Ah, great! Please add this motivation to the PR description.

**Comment by splincode** [comment]
Very good, sir :)

**Comment by arturovt** [comment]
@markwhitfeld @splincode 

All tests are passing!!! :tada:

**Pull request merged**
