### PR TITLE
build(typescript): upgrade to the v3.5

### PR DESCRIPTION
**Pull request by arturovt**
## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Issue Number: #1165 

## What is the new behavior?
Angular 8.2 supports TS 3.5, [related PR](https://github.com/angular/angular/pull/31615)

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by splincode** [comment]
Look

https://github.com/ngxs/store/pull/1194/files

**Comment by arturovt** [comment]
@splincode TS doesn't seem to be updated there, as we waited for the ng 8.2 :D

**Comment by splincode** [comment]
Please fix merge conflict

**Comment by arturovt** [comment]
@splincode can we merge as there are no build/test errors?

**Comment by arturovt** [comment]
P.S. zone.js 0.10 is not officially yet supported, so let's rollback to the supported 0.9

**Pull request merged**
