### PR TITLE
fix(router-plugin): manual path check should not fail for SSR

### PR DESCRIPTION
**Pull request by markwhitfeld**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

The manual path check gives an error when run in SSR.
It doesn't have a big impact other than an error being logged.

Issue Number: N/A

## What is the new behavior?
It uses the correct platform location instead of the browser specific `window.location` object.

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by splincode** [comment]
Test please?

**Comment by arturovt** [comment]
Could you also look at the #1153?

**Comment by markwhitfeld** [comment]
As with the original PR this is very difficult to test as it relies on higher level browser simulation.

**Comment by markwhitfeld** [comment]
@arturovt could you have a look at that related issue?

**Comment by markwhitfeld** [comment]
We can merge this one for the release and then do the next as a bugfix release.

**Comment by arturovt** [comment]
> @arturovt could you have a look at that related issue?

Yes, I can

**Comment by markwhitfeld** [comment]
Awesome thanks!

**Pull request merged**
