### PR TITLE
docs: fix destructuring

### PR DESCRIPTION
**Pull request by mehmet-erim**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by markwhitfeld** [comment]
Should probably rather be `[ _, animals] `

**Comment by mehmet-erim** [comment]
> I think is incorrect fix

Just try, it is working :)

```ts
 this.store
      .dispatch(new ProfileGet())
      .pipe(
        withLatestFrom(this.profile$),
        take(1),
      )
      .subscribe(([, profile]) => { }
```
I tried.

**Comment by armanozak** [comment]
> Should probably rather be `[ _, animals] `

`[, animals]` is valid JavaScript.

**Comment by arturovt** [comment]
@armanozak @mehmet-erim 
Yes it's valid.

**Comment by arturovt** [comment]
@mehmet-erim 
Please update commit title and PR body according our template.

**Comment by mehmet-erim** [comment]
> @mehmet-erim
> Please update commit title and PR body according our template.

Updated

**Comment by arturovt** [comment]
@mehmet-erim Thank you :tada:

**Comment by markwhitfeld** [comment]
I understand that `[, animals]` is valid JavaScript, but these are docs so readability is better than code that is valid but could be misunderstood.
This is why I suggested the underscore. The blank parameter is just not obvious enough. Maybe a variable name could be better?

**Comment by armanozak** [comment]
Hey @markwhitfeld 

I see your point. It was misunderstood due to the context. 

I agree with you on the fact that most people would understand an underscore better than omission of any variable name. A clear variable name may also prove better as you’ve suggested.

**Comment by markwhitfeld** [comment]
@mehmet-erim Are you going to update accordingly?

**Comment by mehmet-erim** [comment]
> @mehmet-erim Are you going to update accordingly?

I updated. Is that okay?

**Pull request merged**
