### PR TITLE
docs(store): update incorrect number of pipes

### PR DESCRIPTION
**Pull request by schuchard**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fixing the docs.

Issue Number: N/A

## What is the new behavior?
Updated docs

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by arturovt** [comment]
@schuchard Wait, I've only noticed after merging - why do you push to the `release` branch not `master`?

**Comment by eranshmil** [comment]
The number is unnecessary.
"... we can use the following pipes:"

**Comment by arturovt** [comment]
@eranshmil :+1: 
I think it's needed to do another PR but pushing into `master`, not `release`.

**Comment by markwhitfeld** [comment]
@schuchard You did as was intended ;-)
@arturovt This is correct that these docs updates would go to the `release` branch because we want them to be visible on the main docs pages. 
@eranshmil I merge these changes into `master` whenever I see them come through.

**Comment by arturovt** [comment]
@markwhitfeld Thanks for clarifying

**Pull request merged**
