### PR TITLE
fix(logger): log group not closed on error

### PR DESCRIPTION
**Pull request by eranshmil**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
image

Issue Number: #817 

## What is the new behavior?
I added the `error` log in case the error raised is suppressed with a custom error handler after the logger ran.
image

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by splincode** [comment]
@markwhitfeld yes of course
My custom logger
https://github.com/splincodewd/client-logger

Test for logger
https://github.com/splincodewd/client-logger/blob/master/src/plugins/console-group-api/console-group-api.spec.ts

**Comment by splincode** [comment]
https://github.com/splincodewd/client-logger/blob/master/src/utils/spec-helpers/converter.ts

**Comment by splincode** [comment]
I think we need to make testing tools. `@ngxs/store/testing`

**Comment by eranshmil** [comment]
> Awesome work!
> Is it possible to add a test for this?

Yeah, that's my next task in this matter, but I wanted to get this fix in the next version.

**Comment by markwhitfeld** [comment]
Agreed. I think that testing tools are high on the agenda for the next release.
@eranshmil are you going to get a chance to add the test?
Aiming for release tomorrow

**Comment by splincode** [comment]
@markwhitfeld I think you need to add it to the release, add tests later.

**Comment by eranshmil** [comment]
> Agreed. I think that testing tools are high on the agenda for the next release.
> @eranshmil are you going to get a chance to add the test?
> Aiming for release tomorrow

I'm currently working on them, but not quite sure if I'll finish them until tomorrow.

**Comment by splincode** [comment]
@markwhitfeld Can we suspend release?

**Comment by splincode** [comment]
@markwhitfeld ping

**Comment by arturovt** [comment]
@markwhitfeld ping :rocket:

**Pull request merged**
