### PR TITLE
Feature/async storage plugin

### LINKED ISSUE #1749: 🚀[FEATURE]: Support async storage in storage plugin
Related issues: #896 #221 
Related PRs: [#669](https://github.com/ngxs/store/pull/669) [#814](https://github.com/ngxs/store/pull/814) [#842](https://github.com/ngxs/store/pull/842)

### Relevant Package
This feature request is for @ngxs/storage-plugin

### Description
The current @ngxs/storage-plugin does not support asynchronous or observable-based storage engines, making it difficult to use NGXS and data persistence in PWAs.

### Describe the problem you are trying to solve
Allow use of NGXS with offline persistence storage options for PWAs.

### Describe the solution you'd like
Either:
- @ngxs/storage-plugin updated to include async storage engines
- [@ngxs-labs/async-storage-plugin](https://github.com/ngxs-labs/async-storage-plugin) updated to be stable and production ready, as the last commit/release is in 2019 and is not a stable, production ready release due to the "WIP" status
- A new NGXS plugin created and maintained for asynchronous storage persistence

### Describe alternatives you've considered
- @ngxs-labs/async-storage-plugin - unstable and no updates since 2019
- [https://github.com/kxc0re/store/tree/async-plugin](https://github.com/kxc0re/store/tree/async-plugin) - even older than @ngxs-labs/async-storage-plugin and not maintained

### Extra notes
This implementation could possibly be simplified by using this npm package [@ngx-pwa/local-storage](https://www.npmjs.com/package/@ngx-pwa/local-storage) as it implements a localStorage-like API for Indexed DB.

It could also simplify the implementation by using [localForage](https://github.com/localForage/localForage).

The lack of up to date and stable async/observable-based storage options is makes it very hard to consider NGXS as a state management library when PWA support is absolutely necessary, especially when [Akita supports and mentions this on the wiki](https://datorama.github.io/akita/docs/enhancers/persist-state/#async-support)

### PR DESCRIPTION
**Pull request by AllySummers**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Adding new storage plugin that supports persisting states to multiple different storage engines, including asynchronous and observable-based ones

Issue Number:
Fixes #1749

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

At this point in time, I have not added tests for this plugin yet. I would like to seek some support in the creation of this plugin as it is my first plugin in NGXS and I am not very experienced in NGXS.

This plugin allows the use of multiple storage engines (default options are local storage, session storage or indexed db through local forage) and to choose which storage engine per state key.

I have created a very simple demo project for this plugin [here](https://github.com/AllySummers/ngxs-async-demo-project).

Current issue that I would appreciate help with is identifying where my code fails to return the retrieved value from the storage engine. If you run the demo project, you can see it retrieves the value in one of the console logs but is not returned somewhere.

Apologies if there is anything wrong with this PR.

### CODE REVIEW

**Review by markwhitfeld — COMMENTED** [review]
Thank you for the immense effort you put into this PR!!!

I have made a number of code suggestions to fix the bugs.
There is a lot of confusion between variables and many mutations.

I would recommend extracting some of the steps, like deserialise/serialise and runMigration into their own functions that do not have access to modify the variables in the closure of the handle function and to rather return the values they have updated. Note: you would have to run reduce for your migrations as opposed to forEach to get the new modified/unmodified value
This will make the code much cleaner, easier to read and help to prevent side effects.

**Comment by markwhitfeld** [comment]
Ok, so now for the topic of this plugin...
I am so glad that you did some decent research in your logged issue about existing solutions here.

We prefer not to accept a new plugin directly into the core repo, but prefer to have these fleshed out in the NGXS labs first. I like the API of this plugin and I would really like to have a comparison between the different libs and what the pros and cons are between each.

I am thinking that if @AllySummers, @marcjulian and @davidmorissette put their heads together then we could come up with an amazing storage plugin replacement for the core storage plugin that is next level!!! What do you all think?

If each of you could ping me on slack so that I can get your username and I will add you to a dedicated channel for this work (if you would like to be involved) 👍

**Comment by AllySummers** [comment]
> Ok, so now for the topic of this plugin...
> I am so glad that you did some decent research in your logged issue #1749 about existing solutions.
> 
> We prefer not to accept a new plugin directly into the core repo, but prefer to have these fleshed out in the NGXS labs first. I like the API of this plugin and I would really like to have a comparison between the different libs and what the pros and cons are between each.
> 
> I am thinking that if @AllySummers, @marcjulian and @davidmorissette put their heads together then we could come up with an amazing storage plugin replacement for the core storage plugin that is next level!!! What do you all think?
> 
> If each of you could ping me on slack so that I can get your username and I will add you to a dedicated channel for this work (if you would like to be involved) 👍
> 
> PS. Maybe @JanMalch from https://www.npmjs.com/package/ngxs-electron-storage or @ThomasIommi from https://www.npmjs.com/package/@iommi/ngxs-ionic-storage might also want to weigh in!

I have PM'd you on slack so you know my username there, but will respond to your comments here.

My apologies, I wasn't aware you didn't want new plugins in this repo. I also wasn't sure if the existing storage plugin shouldn't be replaced, as it would likely bring breaking changes.

The electron storage plugin looks to be abandoned, as it has not been updated in 3 years and is archived on GitHub.

I wasn't aware the ionic storage plugin already existed either, although it does possibly have a slightly different use case.

Possibly we could implement a few extra default storage engines, to cover use in PWA, ionic and electron? I imagine the whole list would be this?
- LocalStorage
- SessionStorage
- IndexedDB
- WebSQL
- SQLite
- File

Based on my idea of how the storage plugin should work, all of them would ideally work and just be an implementation of a storage engine class (but ship with the plugin), as this plugin would allow use of synchronous, asynchronous or observable-based storage engines.

As for a comparison of the different storage libraries, I think there is possibly a feature or 2 from each implementation that would be nice to bring together into one solution.
- Electron storage plugin for it's debouce time option
- Ionic storage plugin for its option to provide fallback storage options
- This implementation, as it allows you to persist different state keys in different storage engines - it seems other options are limited to 1 storage engine? (Unless you can import the module multiple times?)

Also thank you for your comments on my code. This is my first NGXS plugin (and first real open source contribution), so it's probably all kinds of wrong, but I will hopefully be able to address those and work on it more on the weekend. :)

**Comment by AllySummers** [comment]
@markwhitfeld Thank you very much for your helpful code suggestions. I made the changes suggested and as far as I can tell, the plugin is working as expected although obviously unit tests need to be written to test this - which I plan to write when I have time.

Apologies for some of the silly mistakes, I have a very limited understanding of how plugins work in NGXS and tried to use a previous effort as a reference.

**Comment by AllySummers** [comment]
Closing this PR as I will be creating a new PR after the decisions made in #1771 and starting from scratch.

**Pull request closed without merging**
