### PR TITLE
test(store): whole check in simplePatch

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by splincode** [comment]
> We should really only be patching object literals and not prototypal objects.
Yes, this test shows that we have a bug and therefore we need to fix it in the future

**Comment by markwhitfeld** [comment]
The test is demonstrating that priories from the prototype would be copied. This is the behaviour I would expect if you did pass a class created in this way as the original.
What are you saying is the bug?

**Comment by splincode** [comment]
@markwhitfeld @arturovt 
https://stackoverflow.com/a/32422910

We have non-obvious behavior

setState((state) => { ...state, value: 1 }); // shallow copy origin state
patchState({ value: 1 }); // deep copy origin state

**Comment by markwhitfeld** [comment]
Ok, I think I am getting a better idea of the issue you are raising.
Doe this test currently pass?
The object spread operator should only copy the own properties as far as I understand.

**Comment by splincode** [comment]
Current behavior

image

Expected behavior
image

**Comment by markwhitfeld** [comment]
The test does not quite show this scenario that you describe now . 
`val` in the case of this code is the patch value being passed in, not the original value.
The original value is being spread. Your test would show that the original would lose any prototype properties because of the use if spread.

**Pull request closed without merging**
