### PR TITLE
test(store): add @ngxs/store/internal/testing

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the new behavior?

own ability to manage testing more convenient

```TS
import { NgxsTestBed } from '@ngxs/store/testing';

describe('Zoo', () => {

  it('it toggles feed', (done) => {
    const { store } = NgxsTestBed.configureTestingState([ ZooState ]);

    store.dispatch(new FeedAnimals());
    store.selectOnce(state => state.zoo.feed).subscribe(feed => {
      expect(feed).toBe(true);
      done();
    });
  });

});
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by markwhitfeld** [comment]
@splincode What does this provide to the user that could not just be done simply through `TestBed`?

**Comment by splincode** [comment]
- First, at least we can get rid of the use of scattered setup functions in our code.

image

- Secondly, using the usual TestBed users can not catch the method call `ngxsAfterBootrstap` in their state. Thanks to our wrapper, users can always test the full life cycle.

- Third, we can now implement related issues:

https://github.com/ngxs/store/issues/1007
https://github.com/ngxs/store/issues/950
https://github.com/ngxs/store/issues/843
https://github.com/ngxs/store/issues/833
https://github.com/ngxs/store/issues/482
https://github.com/ngxs/store/issues/533

- Improved testing

```
describe('Zoo', () => {
  let store: Store;

  beforeEach(() => {
     const describer = NgxsTestBed.configureTestingState(
            [ ZooState ],
            { developmentMode: false  },
           [ 
              FeatureModule,
              NgxsStoragePluginModule.forRoot() 
           ]
     );

     store = describer.store;
  })

  it('it toggles feed', (done) => {
     // use store
  });

});
```

**Comment by markwhitfeld** [comment]
I believe that the creation of a `@ngxs/store/testing` package is essential and a high priority but I think that we need to take small steps to improve this. We need to create a coherent API that covers all testing needs.

IMO, the feature introduced by this particular PR is more focused on testing the `ngxsAfterBootstrap` in their state, not so much the general setup method. I also would not want to add a TestBed that does all the additional work for triggering the bootstrap but adds an additional cost to each test. Not ideal for unit testing.

I propose the following:
- We create a `@ngxs-labs/testing` labs project so that we can quickly experiment, iterate and get feedback
- We create helpers that directly solve each of the problems listed in the issues above
- We elicit as much feeback/contribution as possible from the community
- Then get it into the `@ngxs/store/testing` lib ASAP!

**Comment by markwhitfeld** [comment]
PS. Down the line if we do end up creating our own `NgxsTestBed.configureTestingState` I would think it would be better to have a method signature that is compatible with the Angular `TestBed.configureTestingState`, but ours just adds additional configuration options and returns a describer that contains `store` and other objects convenient for ngxs testing.

**Comment by splincode** [comment]
@markwhitfeld One of the main problems, why I don’t want to do this in a lab project, is because it’s not convenient to test on our internal tests.  Having translated internal tests for our development we will be able to work out the API ourselves.

**Comment by markwhitfeld** [comment]
Ok, could we then make these test helpers internal to our tests for now then?
We can move them to the sub package later

**Comment by splincode** [comment]
`@ngxs/store/experimental/testing`

**Comment by uiii** [comment]
Hi, my intention to report the issue #1007  was I started creating unit tests. But I'm not skilled at it and work with ngxs only few weeks. As I studied, I've found out unit test should really test only one unit of code and all dependencies shloud be mocked as much as possible. This make sense to me. What I didn't like at action testing as described here: https://ngxs.gitbook.io/ngxs/recipes/unit-testing is that the store is set up and the action is actually dispatched which may cause side-effects so it is more like integration testing. Few days ago I've found new way how to accomplish clean unit testing and it is mocking the action context and run the action handler directly without dispatching the action:

```ts
let indexState: IndexState
let indexStateContextMock: StateContextMock<IndexStateModel>

beforeEach(() => {
    indexState = new IndexState(indexServiceMock)
    indexStateContextMock = mockStateContext<IndexStateModel>(IndexState) 
})

it('should fetch modules', async (done) => {
    indexState.fetchModules(indexStateContextMock, new FetchModules).subscribe(() => {
        await expect(IndexState.getPending(indexStateContextMock.getState())).toBeTruthy()
        await expect(indexStateContextMock.dispatch).toHaveBeenCalledWith(new ModulesFetched(fetchedModulesFixture))
        done()
    })
})
```

the mock helpers are this:

```ts
export type StateContextMock<T> = jasmine.SpyObj<StateContext<T>>

export function mockStateContext<T>(stateClass: any): StateContextMock<T> {
    let values = stateClass['NGXS_OPTIONS_META'].defaults

    return {
        getState: jasmine.createSpy('getState').and.callFake(() => values),
        setState: jasmine.createSpy('setState').and.callFake((val: T) => values = val),
        patchState: jasmine.createSpy('setState').and.callFake((val: Partial<T>) => values = { ...values, ...val }),
        dispatch: jasmine.createSpy('dispatch').and.callFake(() => of())
    }
}
```

I'm quite happy with it. There is one problem that I have to use the `'NGXS_OPTIONS_META'` constant directly because I can't import it as it is in internal package.

**Comment by uiii** [comment]
My colleague mentioned that with this I didn't test if the action decorator is correctly set with the appropriest action handler. I solved it with checking the action handler metadata. This is not possibly ideal becaouse it relies on internal stuff but i works.

```ts
export function getActionFunctions(stateClass: any, actionClass: any): Function[] {
    return stateClass['NGXS_META'].actions[actionClass.type].map(meta => stateClass.prototype[meta.fn])
}

...

it('should have fetch modules action function', async () => {
    await expect(getActionFunctions(IndexState, FetchModules)).toContain(indexState.fetchModules)
})
```

**Comment by splincode** [comment]
@markwhitfeld ping

**Comment by splincode** [comment]
@markwhitfeld I add this PR for internal testing and fixes
https://github.com/ngxs/store/issues/917

**Comment by markwhitfeld** [comment]
@splincode sorry I didn't get back to you. I have had a very busy week.
It's internal, so we can iterate in this a bit. Can always ship it to a labs package later if we choose to go that way as the first public api of this.

**Pull request merged**
