### PR TITLE
fix(store): add static implements for store action

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

image

## What is the new behavior?

Ability to specify an interface for static fields for actions

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by splincode** [comment]
@markwhitfeld 

If you comment out this code

image

The code will not be compiled! Thus, we do not need to write meaningless comments, but simply use the desired decorator for service shots.

image

**Comment by splincode** [comment]
@markwhitfeld In your case, even if people would write a comment, but confused and did not add a static property, the code would compile, but this would not work for users. You yourself care about the clean code, however, comments in code that can be easily changed or removed by someone will not protect you, unlike this type-safe decorator.

**Comment by splincode** [comment]
@arturovt @eranshmil what do you think?

**Comment by markwhitfeld** [comment]
The comment is detailing a stop gap measure which is in place while we are still supporting TS 2.x
PS. I am also investigating if we could possibly make the `type` property on actions optional so not to keen to introduce a new construct around that property.

**Comment by deebloo** [comment]
I am getting concerned about API surface size. Is this absolutely necessary?

**Comment by markwhitfeld** [comment]
Yeah, my concern as well.

**Comment by eranshmil** [comment]
> @arturovt @eranshmil what do you think?

I think we should leave it for now.
I'm planning to check whether this is still necessary in order to support TS2.*.
No matter what, I guess we will have to drop support in the next year and then we could remove that.

**Pull request closed without merging**
