### PR TITLE
build: migrate to ESLint from TSLint

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: https://github.com/ngxs/store/issues/1584

## What is the new behavior?

TSLint has been the recommended linter in the past but now TSLint is deprecated and ESLint is taking over its duties. This PR will help you migrate from TSLint to ESLint.

https://github.com/palantir/tslint/issues/4534

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by markwhitfeld** [comment]
I know that this has been in the pipeline for a while now, but is it time to switch?
Have they reached feature parity?
Is it generally recommended?

**Comment by arturovt** [comment]
I guess it was worth discussing and then PR, as we talked in chat.

**Comment by splincode** [comment]
any news?

**Comment by markwhitfeld** [comment]
@splincode Please could you answer my questions above?
Also, as mentioned in private chat:
> Around the infrastructure, I plan to do a major rework on the infrastructure soon (considering nx workspaces), so maybe just hold back on this type of task for a bit.

**Comment by markwhitfeld** [comment]
Also, as mentioned in private chat:
> Around the infrastructure, I plan to do a major rework on the infrastructure soon (considering nx workspaces), so maybe just hold back on this type of task for a bit.

**Comment by splincode** [comment]
@markwhitfeld 

> I know that this has been in the pipeline for a while now, but is it time to switch?

We can try to keep up with the times and explore)

> Have they reached feature parity?

Yes, I use https://github.com/typescript-eslint/tslint-to-eslint-config for migrate our tslint.json

> Is it generally recommended?

TSLint full deprecated after December 2020, will be close project

**Comment by splincode** [comment]
@markwhitfeld https://github.com/palantir/tslint/issues/4534

```
As you may have read in this blog post, we plan to deprecate TSLint in 2019 and support the migration to ESLint as the standard linter for both TypeScript & JavaScript. This will not be an immediate deprecation; on the contrary, there is a lot of work to do to ensure a smooth transition to the new tooling without any regressions. There are features, test suites, and conveniences in TSLint which we hope to retain in the migration. There may be a period of time when there is overlap between the two tools and TSLint early adopters are recommended to run both linters to ensure full code check coverage (to a reasonable degree such that performance doesn't suffer drastically).

I will be closing some feature requests in this repo which now feel out of scope because we expect them to be handled in the ESLint / typescript-eslint roadmap. One example of a category of rules for which new feature requests are most likely to be closed / rejected is formatting rules. I have suggested splitting out these rules for quite some time because we use Prettier at Palantir and consider it a better tool for the job of formatting code.

TSLint will continue to release with important bug fixes and updates which keep it up-to-date with the latest compiler / language features.

Update (June 2019): a more concrete roadmap timeline, coordinated with @JoshuaKGoldberg and tslint-contrib-microsoft:

August 1st, 2019: Stop accepting new core rules. Still accept bug fixes, minor features, and rule enhancements. Custom rules are always an option and can be maintained outside this repo.
November 1st, 2019: Stop accepting features or rule enhancements (with the exception of ones that make migrating to typescript-eslint easier). Still accept bug fixes.
January 1st, 2020: Stop accepting anything except security fixes and fixes for crashes introduced by breaking TypeScript changes.
December 1st, 2020: Stop accepting any PRs 🎉
Update (August 2019): see tslint-to-eslint-config for a CLI command that migrates TSLint configuration files to ESLint configuration files.

Update (March 2020): Added "and fixes for crashes introduced by breaking TypeScript changes" to the January 1st deadline, following discussion in #4914.
```

**Pull request closed without merging**
