### PR TITLE
fix(router-plugin): dispatch `RouterNavigation` right away after the necessary event

### PR DESCRIPTION
**Pull request by arturovt**
## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Issue Number: #922 #946 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by eranshmil** [comment]
Does it mean that the same state will be triggered twice? (In case of `GuardsCheckEnd` + `ResolveEnd`)
And please fix the two failing tests, caused by the same error:
```ts
ERROR: /home/travis/build/ngxs/store/packages/router-plugin/tests/router.plugin.spec.ts:183:27 - Shadowed name: 'store'
```

**Comment by arturovt** [comment]
This is a vicious circle which I'm stuck in.
The `ResolveEnd` event is triggered only in cases if some route has some linked resolvers. The `GuardsCheckEnd` event is triggered always.
If I dispatch `RouterNavigation` event after the `NavigationEnd` is triggered - than we cannot access `RouterState` inside selectors.

**Comment by markwhitfeld** [comment]
@arturovt, not considering the required data, where do you think would be the ideal place to dispatch the action?

**Comment by arturovt** [comment]
@markwhitfeld To prevent breaking changes for our users, I'd say the ideal place is in `NavigationEnd`. The problem is users want to access the `router` state on the initial load, and it's not possible when the `RouterNavigation` action is dispatched after `NavigationEnd`.
Paradoxically :joy: :joy: I'd like to hear your thoughts.

**Comment by markwhitfeld** [comment]
After discussing, we decided to add a new `RouterDataResolved` Action that represents the event when the data has been resolved. The `RouterNavigation` Action will be dispatched on GuardCheckEnd because this event is always executed and is the last guaranteed event before the component's constructor is called. The `RouterDataResolved` Action will also update the state, but this will only happen if there are resolvers attached to the route.
This work has been moved to PR #939 and this PR has been closed without merging.

**Pull request closed without merging**
