### PR TITLE
Introducing NGXS Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [NGXS Guru](https://gurubase.io/g/ngxs) to Gurubase. NGXS Guru uses the data from this repo and data from the [docs](https://ngxs.io/) to answer questions by leveraging the LLM.

In this PR, I showcased the "NGXS Guru", which highlights that NGXS now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable NGXS Guru in Gurubase, just let me know that's totally fine.

### CODE REVIEW

**Review by markwhitfeld — APPROVED** [review]
I'm happy to add this.
@kursataktas a few questions for you:
1) Do any questions asked to the guru become cached permalink results? If so, for how long? It seems like I can share the link to a question that GuruBase answered and it returns the result instantly for subsequent calls to the same link.
2) Would it be ok to link to some gurubase answers in an FAQ section of our docs?
3) And lastly, how could we refresh a link if the answer should be regenerated based on the latest version of the docs?

**Comment by kursataktas** [comment]
> I'm happy to add this. @kursataktas a few questions for you:
> 
> 1. Do any questions asked to the guru become cached permalink results? If so, for how long? It seems like I can share the link to a question that GuruBase answered and it returns the result instantly for subsequent calls to the same link.
> 2. Would it be ok to link to some gurubase answers in an FAQ section of our docs?
> 3. And lastly, how could we refresh a link if the answer should be regenerated based on the latest version of the docs?

Thanks for the review, @markwhitfeld 

1. Yes, that's correct.
2. Sure, I can add it as well if you can guide me.
3. If any data source changes, NGXS Guru regenerates answers for all cached questions. You can check the "Last Modified Date" section at the beginning of the answer to verify this. To edit data sources, you need to be a maintainer of the Guru. There is detailed information available [in this repository.](https://github.com/getanteon/gurubase)

**Review by markwhitfeld — APPROVED** [review]

**Comment by kursataktas** [comment]
Hello @markwhitfeld,

We recently released the embeddable "Ask AI" widget, which allows you to integrate your Guru’s Q&A capability into websites, documentation, and more.

The installation process is straightforward, as explained in [this GitHub repository](https://github.com/getanteon/gurubase-widget).

You can see it in action on the [Anteon](https://getanteon.com/) and [NetAlertX](https://netalertx.com/) websites.

**Comment by markwhitfeld** [comment]
> Hello @markwhitfeld,
> 
> We recently released the embeddable "Ask AI" widget, which allows you to integrate your Guru’s Q&A capability into websites, documentation, and more.
> 
> The installation process is straightforward, as explained in [this GitHub repository](https://github.com/getanteon/gurubase-widget).
> 
> You can see it in action on the [Anteon](https://getanteon.com/) and [NetAlertX](https://netalertx.com/) websites.

We would love this, but we use GitBook, so we are blocked until this issue is resolved:
https://github.com/Gurubase/gurubase-widget/issues/7

**Comment by markwhitfeld** [comment]
Added successfully to our GitBook 🎉 
Thank you for creating the integration!
image

**Comment by kursataktas** [comment]
Looks fantastic!

**Pull request merged**
