### PR TITLE
feat(storage-plugin): add suppressErrors option

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: https://github.com/ngxs/store/issues/1439

I constantly see errors in my code in tests, although everything is fine in runtime

## What is the new behavior?

```ts
{
          imports: [
            NgxsModule.forRoot([MyCounterState]),
            NgxsStoragePluginModule.forRoot({ 
                 key: [MyCounterState], 
                 suppressErrors: env.production || env.headlessMode
            })
          ]
}
```

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by splincode** [comment]
@arturovt Could you at least take a look?

**Comment by arturovt** [comment]
> @arturovt Could you at least take a look?

Yes :)

**Comment by arturovt** [comment]
Umm. Not sure if we need this feature... As this is only my subjective opinion so let's wait for the Mark's response. If he's OK with it then I'm also OK.

**Comment by splincode** [comment]
@arturovt It turned out to be very profitable for me in my project

**Comment by markwhitfeld** [comment]
Hmmm.... I am wondering if there is a different way to solve this?
Couldn't the storage module be excluded from the app module in test mode?

**Pull request closed without merging**
