### PR TITLE
feat(store): add freeze decorator

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the new behavior?

Improved freeze actions (If you want to use them)

```ts
import { Freeze } from '@ngxs/store';

@Freeze()
export class Announce {
  static type = '[Announce] action';
  constructor(public artist: Artist) { }
}

@State<Artist>({ .. })
export class ArtistState {

  @Action(Announce)
  public set({ getState, setState }, { artist }: Announce) {    
      artist = null; // TypeError: Cannot assign to read only property 'artist' of object '[object Object]'`
      setState({ ...artist });
  }

}
```

deep

```TS
import { Freeze, unfreeze } from '@ngxs/store';

@State<Artist>({ .. })
export class ArtistState {

  @Action(Announce)
  public set({ getState, setState }, { artist }: Announce) {    

     if (artist.name = "Elvis Presley") { // TypeError: TypeError: Can't add property 'name', object is not extensible
          console.log("The King");
      } else {
          console.log(artist.name);
      }

      setState({ ...unfreeze(artist) });

  }

}
``` 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by markwhitfeld** [comment]
Do you know about the `developmentMode` setting? It does exactly this without the need for a decorator and can be turned off for production build.

**Comment by splincode** [comment]
@markwhitfeld why some tests are marked as xit?
image

**Comment by markwhitfeld** [comment]
This ignores the tests. I can't remember the specific reasons why they were ignored though. Please submit a PR for the re-enabling of them if they work once enabled.

**Comment by markwhitfeld** [comment]
Ah I remember why we disabled that test. Because we were freezing the action and it caused issues with the router plugin because the router plugin was including the Angular route in the action. So we removed the freezing of the action and disabled the test.

**Pull request closed without merging**
