### PR TITLE
docs: add svg logos

### PR DESCRIPTION
**Pull request by adisreyaj**
Adds Horizontal and Vertical NGXS logos in SVG format

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: https://github.com/ngxs/store/issues/1600

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by markwhitfeld — APPROVED** [review]
Awesome work! Nicely done.

**Comment by adisreyaj** [comment]
> Awesome work! Nicely done.

Thanks, @markwhitfeld.
I picked the color from the existing png icon, so it might not be accurate. So If you can provide the brand color code, I can verify and fix it if required.

**Comment by markwhitfeld** [comment]
You are welcome to add another PR, swapping out the png usages for your svgs 👍

**Comment by markwhitfeld** [comment]
What you see is what you get regarding colour! Thanks!

**Comment by splincode** [comment]
image

**Comment by markwhitfeld** [comment]
@splincode, do you have any idea why adding an svg file to the assets folder would make the integration test fail its bundle size?

**Pull request merged**
