### PR TITLE
docs: introduce schematics

### PR DESCRIPTION
**Pull request by profanis**
This PR has a dependency on https://github.com/ngxs/store/pull/2032

### CODE REVIEW

**Review by markwhitfeld — COMMENTED** [review]
What do you think about having a schematics page that has all of this info, and then the necessary sections link to that page?
Or we add a schematics page that could list the different schematics and link to these sections on these different pages.
I'm neither way on this. What do you think?

**Comment by profanis** [comment]
> What do you think about having a schematics page that has all of this info, and then the necessary sections link to that page? Or we add a schematics page that could list the different schematics and link to these sections on these different pages. I'm neither way on this. What do you think?

That was my first approach. I then put myself in the shoes of a newcomer and decided to change that. A newcomer will visit the documentation and will try to have NGXS in his/her application by following more or less a step-by-step flow. 
Other than the newcomer, an experienced user might need to visit the documentation to refresh his/her memory of how to create, for example, an action. Will visit the Actions menu item to read more about that and see the details of the schematic. 
Do you think that this is a valid concern?

**Comment by markwhitfeld** [comment]
Then I am happy to keep it  as is, but can we just add a Schematics page that just lists out the different schematics, and links out to the sections of the pages that you have listed.
PS. can you also change the summary page back to using the `-` instead of the `*` so that the change remains focused on what this PR needs 👍 (we can change the list representation in a later PR).

**Comment by profanis** [comment]
> Then I am happy to keep it as is, but can we just add a Schematics page that just lists out the different schematics, and links out to the sections of the pages that you have listed. PS. can you also change the summary page back to using the `-` instead of the `*` so that the change remains focused on what this PR needs 👍 (we can change the list representation in a later PR).

I have integrated gitbook on my fork to have a visual representation of what I am doing. I assume it auto changed the Summary page. I am reverting it back

**Comment by profanis** [comment]
I am closing this PR since GITBOOK integration messed up my commits
New PR https://github.com/ngxs/store/pull/2057

**Pull request closed without merging**
