### PR TITLE
feat(store): add recommendation for enable development mode

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

https://github.com/ngxs/store/issues/622

## What is the new behavior?

image

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

Motivation to enable debug mode

### CODE REVIEW

**Comment by splincode** [comment]
@markwhitfeld what you think?

**Comment by markwhitfeld** [comment]
I have been meaning to do something similar to this. If it is Angular dev mode and you haven't enabled dev mode then show a message, and if it is Angular prod mode and the dev mode is enabled then show a warning.

In v4 we can automatically sync the modes unless explicitly set.

**Comment by splincode** [comment]
@markwhitfeld fixup

**Comment by juliusstoerrle** [comment]
> In v4 we can automatically sync the modes unless explicitly set.

I would like that!

**Comment by markwhitfeld** [comment]
@juliusstoerrle can achieve it like this for now (I think, haven't tried):
```TS
import { isDevMode } from '@angular/core';
...
NgxsModule.forRoot(states, { developmentMode: isDevMode() })
```

**Pull request merged**
