### PR TITLE
chore: update vscode settings

### PR DESCRIPTION
**Pull request by arturovt**
## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] Other... Please describe:
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by deebloo** [comment]
Shouldn't these items be handled by prettier?

**Comment by arturovt** [comment]
@deebloo sure, prettier does its job, but it's more convenient for developers to start coding in this way

**Comment by deebloo** [comment]
Sorry not sure I understand. The prettier formatting should be automatic correct?

**Comment by deebloo** [comment]
Sorry not sure I understand. The prettier formatting should be automatic correct?

**Comment by deebloo** [comment]
I don't want to sound picky I just want to understand the reason for the update.

**Comment by deebloo** [comment]
I don't want to sound picky I just want to understand the reason for the update.

**Comment by arturovt** [comment]
Prettier formats code when you run `git commit`. Thus why do you want to write code in one format and then switch this format when you go to commit? A new question that comes out of it is - why do we need `.editorconfig` then? It's supported in most IDEs except VSCode, because you have to install an extension.

**Comment by markwhitfeld** [comment]
I added the original settings file a few days ago. Was it causing strange behaviour of your formatter?
I have got the Prettier extension installed and it works great, so maybe it would be good to add that as a recommended extension for the workspace...

**Pull request closed without merging**
