### PR TITLE
feat(store): ofAction* methods should have strong types

### LINKED ISSUE #1807: 🚀[FEATURE]: improve types of "ofAction*" functions
### Relevant Package

 This feature request is for @ngxs/store

https://github.com/ngxs/store/blob/master/packages/store/src/operators/of-action.ts

### Description
 
The types of these methods can be significantly improved, currently

### Describe the problem you are trying to solve
 

```typescript
this.store.actions.pipe(
  ofActionSuccessful(MyAction1, MyAction2),
  tap((a/* : any */) => { });
```

type of parameter `a` here is `any`

### Describe the solution you'd like
 

```typescript
this.store.actions.pipe(
  ofActionSuccessful(MyAction1, MyAction2),
  tap((a/* : MyAction1 | MyAction2 */) => { });
```

the type of `a` can be determined by typescript...

This can be accomplished with:

```typescript
type TupleKeys<T extends any[]> = Exclude<keyof T, keyof []>;

type Constructed<T> = T extends { new (...args: any[]): infer U } ? U : T;

export function ofActionSuccessful<T extends ActionType[]>(
  ...allowedTypes: T
): OperatorFunction<ActionContext<Constructed<T[TupleKeys<T>]>>, Constructed<T[TupleKeys<T>]>> {
  // ...
}
```

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

```typescript
this.store.actions.pipe(
  ofActionSuccessful(MyAction1, MyAction2),
  // eslint-disable-next-line: @typescript-eslint/no-unsafe-argument
  tap((a: any) => { });
```

and 

```typescript
this.store.actions.pipe(
  ofActionSuccessful(MyAction1, MyAction2),
  tap((a: any) => { 
  if (a instanceof MyAction1) {
     ...
  }
  if (a instanceof MyAction2) {
    ...
  }
});
```

The vast majority of the time I only need one type here but still I have to work around the eslint rule.

Unfortunately I believe this is a breaking change...

### PR DESCRIPTION
**Pull request by bbarry**
Improving the type definitions of the ofAction pipe operators improves the type of the
rxjs pipe and subscriptions and helps identify bugs in user code.

closes #1807

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #1807

## What is the new behavior?

ofAction* functions now have strong type restrictions (no more `any`)

## Does this PR introduce a breaking change?

```
[X] Yes
[ ] No
```

This change may nominally break application code in that it will uncover existing defects in said code where the application is passing types to these functions which will never be matched, or is attempting to use the pipe downstream in a way that can never occur. Every fix will be case specific and involves correcting the action type definition and/or downstream pipe methods. 

## Other information

Thank you https://github.com/typescript-eslint/typescript-eslint for providing the rule https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-unsafe-argument.md which made me identify a dozen such defects that the changes here also error on.

### CODE REVIEW

**Review by splincode — APPROVED** [review]

**Comment by splincode** [comment]
@arturovt @markwhitfeld could you see please?

**Review by arturovt — APPROVED** [review]
I love the change. Thanks @bbarry . Just to ensure that won't be a breaking change, right?

**Comment by bbarry** [comment]
It depends on what is considered a breaking change.

This change does not introduce any new functionality or have any impact on runtime code at all.

Yet once merged, users running the version post change may find their application fails to compile if they were using these functions in such a way that they already had a defect in their code.

**Comment by arturovt** [comment]
> It depends on what is considered a breaking change.
> 
> This change does not introduce any new functionality or have any impact on runtime code at all.
> 
> Yet once merged, users running the version post change may find their application fails to compile if they were using these functions in such a way that they already had a defect in their code.

Well, that is what considered a breaking change if apps will fail to compile.

**Review by markwhitfeld — CHANGES_REQUESTED** [review]
@bbarry I am a BIG fan of this change, and it aligns perfectly with everything else going into the next minor release. We are adding some massive typings improvements 🎉 .
Could you update the changelog in this PR with a description of this improvement?

Regarding the 'breaking change', I think that even though there may be compile failures when users upgrade to this, it is identifying issues that exist in their code. I would class this as a 'fixing change' instead and a welcome improvement in any codebase.
I can't think of a single case where a user might be unhappy that the upgrade has showcased a bug.

@arturovt and @splincode, I would be happy for this to be included in the next minor release as a non "breaking change" if you agree with my logic here?

**Comment by splincode** [comment]
> I would be happy for this to be included in the next minor release as a non "breaking change" if you agree with my logic here?

I think it's not problem! TypeScript does exactly the same in its minor versions

**Comment by bbarry** [comment]
> Also, a question, is there a minimum version of Typescript that is required for these changes?

I believe the minimum version of typescript for this change is 2.8 but I am unable to test and verify (2.8 is when `Exclude<>` and Conditional Types were added and the changes here are similar to ones described in the documentation for that release).  That said CT are already in use elsewhere in the code (https://github.com/ngxs/store/search?q=infer) so I am thinking nothing has changed?

**Comment by bbarry** [comment]
@markwhitfeld is that description better?

**Comment by markwhitfeld** [comment]
@bbarry Thank you for your updates. Could you add an entry in `./CHANGELOG.md` for this update as part of this PR?

@splincode Unfortunately Typescript does not follow strict semantic versioning because they introduce multiple breaking changes in each minor release, so they are not quite a goldens standard 😁 . But, thank you for your vote on this.

I'll wait to hear from @arturovt too. Hopefully he is still ok with all the bombing going on in his city 😭 .

**Comment by markwhitfeld** [comment]
PS. @bbarry If you are particularly skilled in TypeScript types magic, then please DM me on Twitter (`markwhitfeld`) if you would like to help out with some of the other complex aspects of typing in NGXS.

**Comment by arturovt** [comment]
Hey, as I said I love the change and I don't mind considering it as a _fix_.

**Review by markwhitfeld — APPROVED** [review]

**Comment by markwhitfeld** [comment]
Waoh, that the build on master is failing from merging this PR. I see now that the CI checks never ran on this PR. Very strange indeed.
I'll push a fix.

**Pull request merged**
